name: 'Bockerl Back ì´ìŠˆ ìƒì„±'
description: 'Bockerl Back Repoì— ì´ìŠˆë¥¼ ìƒì„±í•˜ë©°, ìƒì„±ëœ ì´ìŠˆëŠ” Jiraì™€ ì—°ë™ë©ë‹ˆë‹¤.'
labels: [order]
title: 'ì´ìŠˆ ì´ë¦„ì„ ì‘ì„±í•´ì£¼ì„¸ìš”'
body:
  - type: input
    id: parentKey
    attributes:
      label: 'ìƒìœ„ ì‘ì—… Ticket Number'
      description: 'ìƒìœ„ ì‘ì—…ì˜ Ticket Numberë¥¼ ê¸°ì…í•´ì£¼ì„¸ìš”'
      placeholder: 'KAN-00'
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: 'ì´ìŠˆ ë‚´ìš©(Description)'
      description: '# ğŸš€ ê°œë°œí•˜ë©´ì„œ ìƒê¸´ í¬ê³  ì‘ì€ ì´ìŠˆì‚¬í•­ì„ ê¸°ë¡í•´ì£¼ì„¸ìš”'
    validations:
      required: false
  - type: textarea
    id: details
    attributes:
      label: 'ìƒì„¸ ë‚´ìš©(Details)'
      description: 'ğŸ’¡ì–´ë–¤ ê¸°ëŠ¥ì¸ê°€ìš”?'
      value: |
        - About Details
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: 'ì²´í¬ë¦¬ìŠ¤íŠ¸(Tasks)'
      description: 'âœ… To Do'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: 'ì°¸ì¡°(References)'
      description: 'í•´ë‹¹ ì´ìŠˆê³¼ ê´€ë ¨ëœ ë ˆí¼ëŸ°ìŠ¤ë¥¼ ì°¸ì¡°í•´ì£¼ì„¸ìš”'
      value: |
        - Reference1
    validations:
      required: false
